source 'https://rubygems.org'

gem 'bcrypt-ruby',             '3.1.5'
gem 'jquery-rails',            '4.0.3'
gem 'libv8',                   '3.16.14.7'
gem 'oj',                      '2.12.8'
gem 'oj_mimic_json',           '1.0.1'
gem 'pg',                      '>= 0.18.1'
gem 'rails',                   '~> 4.2'
gem 'sass-rails',              '~> 5.0'
gem 'therubyracer',            '0.12.2'
gem 'uglifier',                '>= 1.3.0'
gem 'puma',                    '2.11.3'
gem 'credit_card_validations', '2.0.2'
gem 'grocer', '0.6.1'
gem 'gcm', '0.1.0'
# Gems for background jobs
# gem 'slim',          '>= 1.1.0'
# gem 'sinatra',       '>= 1.3.0'
# gem 'redis',         '= 3.1.0'
# gem 'sidekiq',       '>= 3.3.0'

group :development, :test do
  gem 'capistrano-bundler', '>= 1.1.3'
  gem 'capistrano',         '>= 3.2.1'
  gem 'capistrano-rails',   '>= 1.1.1'
  gem 'capistrano-rvm',     '0.1.2'
  # gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'
  gem 'capistrano3-puma',   '>= 0.5.1', github: 'seuros/capistrano-puma'
  gem 'reqres_rspec',       '0.1.16'
  gem 'rspec-rails',        '~> 3.0'
  gem 'binding_of_caller',  '0.7.2'
  gem 'ruby_parser',        '>= 3.1.1'
  # gem 'better_errors',      '>= 0.3.2'
  gem 'pry-nav',            '~> 0.2.4'
  gem 'pry-rails',          '0.3.4'
  gem 'letter_opener',      '~> 1.2.0'
  # gem 'rubocop', require : false
  # gem 'spring'
end
